#!/usr/bin/env python3
"""Bootstrap a Makefile with recipes for Python modules in the current folder."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


HEADER = "# Auto-generated by dev.py. Edit dev.py, then regenerate."
LIBRARY_MODULE_FILENAME = "devlib.py"


def discover_python_modules(directory: Path) -> list[Path]:
    """Return top-level Python files in the given directory, sorted by filename."""
    return sorted(
        path
        for path in directory.glob("*.py")
        if path.is_file() and not path.name.startswith(".")
    )


def make_target_name(module_file: Path) -> str:
    """Use the module stem as the make target name."""
    return module_file.stem


def build_makefile_content(modules: list[Path]) -> str:
    """Create Makefile content with one recipe per Python module."""
    targets = [make_target_name(module) for module in modules]

    lines: list[str] = [
        HEADER,
        "",
        "PYTHON ?= python3",
        "ARG ?=",
        "ARGS ?=",
        "MODULE ?=",
        "",
        f"PY_TARGETS := {' '.join(targets)}" if targets else "PY_TARGETS :=",
        "",
        ".PHONY: help bootstrap add $(PY_TARGETS)",
        "",
        "help:",
        "\t@echo \"Available Python module targets:\"",
    ]

    if targets:
        lines.append("\t@echo \"  $(PY_TARGETS)\"")
        lines.append("\t@echo \"Run with: make <target>\"")
        lines.append("\t@echo \"Optional args: make <target> ARG='KEY=VALUE'\"")
        lines.append("\t@echo \"Or multiple: make <target> ARGS='KEY1=VALUE1 KEY2=VALUE2'\"")
    else:
        lines.append("\t@echo \"  (none found)\"")

    lines.extend(
        [
            "\t@echo \"Bootstrap/rebuild: make bootstrap\"",
            "\t@echo \"Create module: make add MODULE=<name>\"",
            "\t@echo \"Examples: make query | make hyper-tag | make hyper-analysis\"",
            "",
            "bootstrap:",
            "\t$(PYTHON) dev.py",
            "",
            "add:",
            "\t@test -n \"$(MODULE)\" || (echo \"Usage: make add MODULE=<name>\" && exit 1)",
            "\t$(PYTHON) dev.py add --module \"$(MODULE)\"",
            "",
        ]
    )

    for module in modules:
        target = make_target_name(module)
        recipe = f"\t$(PYTHON) {module.name} $(ARGS) $(ARG)"

        lines.extend(
            [
                f"{target}:",
                recipe,
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def write_makefile(directory: Path, content: str) -> Path:
    """Write Makefile content into the given directory."""
    makefile_path = directory / "Makefile"
    makefile_path.write_text(content, encoding="utf-8")
    return makefile_path


def normalize_module_name(raw_name: str) -> str:
    """Normalize user input into a safe Python module filename stem."""
    module_name = raw_name.strip()
    if module_name.endswith(".py"):
        module_name = module_name[:-3]

    if not module_name:
        raise ValueError("module name must not be empty")

    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_-]*", module_name):
        raise ValueError(
            "module name must start with a letter/underscore and contain only letters, "
            "numbers, underscores, or hyphens"
        )

    return module_name


def build_library_module_content() -> str:
    """Shared helpers imported by scaffolded modules."""
    return """\
\"\"\"Shared utilities for generated development modules.\"\"\"

from __future__ import annotations


def todo(feature: str) -> None:
    \"\"\"Raise a clear placeholder error for unfinished functionality.\"\"\"
    raise NotImplementedError(f\"Implement: {feature}\")


def run(main_func) -> int:
    \"\"\"Run a main function with a consistent KeyboardInterrupt exit code.\"\"\"
    try:
        return int(main_func())
    except KeyboardInterrupt:
        return 130
"""


def build_module_content(module_name: str) -> str:
    """Create scaffold content for a new Python module."""
    return f"""\
\"\"\"{module_name}: generated module scaffold.\"\"\"

from __future__ import annotations

from {Path(LIBRARY_MODULE_FILENAME).stem} import run, todo


def main() -> int:
    todo(\"{module_name}.main\")
    return 0


if __name__ == \"__main__\":
    raise SystemExit(run(main))
"""


def ensure_library_module(directory: Path) -> Path:
    """Create the shared library module if it doesn't already exist."""
    library_path = directory / LIBRARY_MODULE_FILENAME
    if not library_path.exists():
        library_path.write_text(build_library_module_content(), encoding="utf-8")
    return library_path


def add_module(directory: Path, module_name: str) -> Path:
    """Create a new module scaffold and ensure shared helpers exist."""
    normalized_name = normalize_module_name(module_name)
    module_path = directory / f"{normalized_name}.py"

    if module_path.exists():
        raise FileExistsError(f"{module_path.name} already exists")

    ensure_library_module(directory)
    module_path.write_text(build_module_content(normalized_name), encoding="utf-8")
    return module_path


def bootstrap(directory: Path) -> Path:
    """Generate or refresh the Makefile from current Python modules."""
    modules = discover_python_modules(directory)
    content = build_makefile_content(modules)
    makefile_path = write_makefile(directory, content)

    print(f"Wrote {makefile_path}")
    if modules:
        print("Registered targets:", ", ".join(make_target_name(module) for module in modules))
    else:
        print("No Python modules found in current folder.")

    return makefile_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Makefile recipes for Python modules in the current directory."
    )
    subparsers = parser.add_subparsers(dest="command")

    add_parser = subparsers.add_parser("add", help="Create a new Python module scaffold")
    add_parser.add_argument("--module", required=True, help="Module name, with or without .py")

    return parser.parse_args()


def main() -> int:
    args = parse_args()
    current_dir = Path.cwd()

    if args.command == "add":
        try:
            module_path = add_module(current_dir, args.module)
        except (ValueError, FileExistsError) as exc:
            print(f"Error: {exc}")
            return 1

        print(f"Created module: {module_path}")
        library_path = current_dir / LIBRARY_MODULE_FILENAME
        if library_path.exists():
            print(f"Shared library available at: {library_path}")
        bootstrap(current_dir)
        return 0

    bootstrap(current_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())