# Auto-generated by dev.py. Edit dev.py, then regenerate.

PYTHON ?= python3
ARG ?=
ARGS ?=
MODULE ?=

PY_TARGETS := agent check-hosts dev devlib hyper-analysis hyper-tag query visualise-data wow-discussion wow-list-sessions

.PHONY: help bootstrap add $(PY_TARGETS)

help:
	@echo "Available Python module targets:"
	@echo "  $(PY_TARGETS)"
	@echo "Run with: make <target>"
	@echo "Optional args: make <target> ARG='KEY=VALUE'"
	@echo "Or multiple: make <target> ARGS='KEY1=VALUE1 KEY2=VALUE2'"
	@echo "Bootstrap/rebuild: make bootstrap"
	@echo "Create module: make add MODULE=<name>"
	@echo "Examples: make query | make wow-discussion | make hyper-tag"

bootstrap:
	$(PYTHON) dev.py

add:
	@test -n "$(MODULE)" || (echo "Usage: make add MODULE=<name>" && exit 1)
	$(PYTHON) dev.py add --module "$(MODULE)"

agent:
	$(PYTHON) agent.py $(ARGS) $(ARG)

check-hosts:
	$(PYTHON) check-hosts.py $(ARGS) $(ARG)

dev:
	$(PYTHON) dev.py $(ARGS) $(ARG)

devlib:
	$(PYTHON) devlib.py $(ARGS) $(ARG)

hyper-analysis:
	$(PYTHON) hyper-analysis.py $(ARGS) $(ARG)

hyper-tag:
	$(PYTHON) hyper-tag.py $(ARGS) $(ARG)

query:
	$(PYTHON) query.py $(ARGS) $(ARG)

visualise-data:
	$(PYTHON) visualise-data.py $(ARGS) $(ARG)

wow-discussion:
	$(PYTHON) wow-discussion.py $(ARGS) $(ARG)

wow-list-sessions:
	$(PYTHON) wow-list-sessions.py $(ARGS) $(ARG)
