# Auto-generated by bootstrap-make.py. Edit bootstrap-make.py, then regenerate.

PYTHON ?= python3

PY_TARGETS := bootstrap-make bottom-max data-loader devlib enrich_bow get-training-set join-stages runtime top-max

.PHONY: help bootstrap add $(PY_TARGETS)

help:
	@echo "Available Python module targets:"
	@printf '  %-15s\n' 'bootstrap-make'
	@printf '  %-15s\n' 'bottom-max'
	@printf '  %-15s\n' 'data-loader'
	@printf '  %-15s\n' 'devlib'
	@printf '  %-15s\n' 'enrich_bow'
	@printf '  %-15s\n' 'get-training-set'
	@printf '  %-15s\n' 'join-stages'
	@printf '  %-15s\n' 'runtime'
	@echo ""
	@echo "Usage: make <target> KEY=VALUE ..."
	@echo "       make bootstrap"
	@echo "       make add MODULE=<name>"

bootstrap:
	@$(PYTHON) bootstrap-make.py

add:
	@test -n "$(MODULE)" || (echo "Usage: make add MODULE=<name>" && exit 1)
	@$(PYTHON) bootstrap-make.py add --module "$(MODULE)"

	@echo ""
	@echo "join-stages: Chain multiple stages together:"
	@echo "  make join-stages stage1 stage2 ..."

bootstrap-make:
	@$(PYTHON) bootstrap-make.py

bottom-max:
	@$(PYTHON) bottom-max.py

data-loader:
	@$(PYTHON) data-loader.py

devlib:
	@$(PYTHON) devlib.py

enrich_bow:
	@$(PYTHON) enrich_bow.py

get-training-set:
	@$(PYTHON) get-training-set.py

join-stages:
	@$(PYTHON) join-stages.py $(filter-out join-stages,$(MAKECMDGOALS))

runtime:
	@$(PYTHON) runtime.py

top-max:
	@$(PYTHON) top-max.py
