# Auto-generated by bootstrap-make.py. Edit bootstrap-make.py, then regenerate.

PYTHON ?= python3

PY_TARGETS := bootstrap-make bottom-max data-loader devlib enrich_bow extra-rare-agentic-bert get-training-set join-stages runtime stream_subprocess top-max

.PHONY: help bootstrap add $(PY_TARGETS)

help:
	@echo "Available Python module targets:"
	@printf '  %-15s\n' 'bootstrap-make'
	@printf '  %-15s\n' 'bottom-max'
	@printf '  %-15s\n' 'data-loader'
	@printf '  %-15s\n' 'devlib'
	@printf '  %-15s\n' 'enrich_bow'
	@printf '  %-15s\n' 'extra-rare-agentic-bert'
	@printf '  %-15s\n' 'get-training-set'
	@printf '  %-15s\n' 'join-stages'
	@echo ""
	@echo "Usage: make <target> KEY=VALUE ..."
	@echo "       make bootstrap"
	@echo "       make add MODULE=<name>"

bootstrap:
	@$(PYTHON) src/python/bootstrap-make.py

add:
	@test -n "$(MODULE)" || (echo "Usage: make add MODULE=<name>" && exit 1)
	@$(PYTHON) src/python/bootstrap-make.py add --module "$(MODULE)"

	@echo ""
	@echo "join-stages: Chain multiple stages together:"
	@echo "  make join-stages stage1 stage2 ..."

bootstrap-make:
	@$(PYTHON) src/python/bootstrap-make.py

bottom-max:
	@$(PYTHON) src/python/bottom-max.py

data-loader:
	@$(PYTHON) src/python/data-loader.py

devlib:
	@$(PYTHON) src/python/devlib.py

enrich_bow:
	@$(PYTHON) src/python/enrich_bow.py

extra-rare-agentic-bert:
	@$(PYTHON) src/python/extra-rare-agentic-bert.py

get-training-set:
	@$(PYTHON) src/python/get-training-set.py

join-stages:
	@$(PYTHON) src/python/join-stages.py $(filter-out join-stages,$(MAKECMDGOALS))

runtime:
	@$(PYTHON) src/python/runtime.py

stream_subprocess:
	@$(PYTHON) src/python/stream_subprocess.py

top-max:
	@$(PYTHON) src/python/top-max.py
