#!/usr/bin/env python3
"""Bootstrap a Makefile with recipes for Python modules.

Modules are discovered under ``src/python/`` (relative to the project root)
and the generated Makefile lives at the project root. Recipes invoke each
module via ``python3 src/python/<module>.py``.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


HEADER = "# Auto-generated by bootstrap-make.py. Edit bootstrap-make.py, then regenerate."
LIBRARY_MODULE_FILENAME = "devlib.py"
PYTHON_MODULES_DIR = Path("src") / "python"


def discover_python_modules(directory: Path) -> list[Path]:
    """Return top-level Python files in ``directory``, sorted by filename."""
    return sorted(
        path
        for path in directory.glob("*.py")
        if path.is_file() and not path.name.startswith(".")
    )


def make_target_name(module_file: Path) -> str:
    """Use the module stem as the make target name."""
    return module_file.stem


def build_makefile_content(modules: list[Path]) -> str:
    """Create Makefile content with one recipe per Python module.

    ``modules`` are paths relative to the project root (currently always
    under ``src/python/``) so the emitted recipes reference them via
    ``src/python/<module>.py``.
    """
    targets = [make_target_name(module) for module in modules]
    module_relpath = {make_target_name(module): str(module).replace("\\", "/") for module in modules}

    lines: list[str] = [
        HEADER,
        "",
        "PYTHON ?= python3",
        "",
        f"PY_TARGETS := {' '.join(targets)}" if targets else "PY_TARGETS :=",
        "",
        ".PHONY: help bootstrap add $(PY_TARGETS)",
        "",
        "help:",
        "\t@echo \"Available Python module targets:\"",
    ]

    if targets:
        for target in targets[:8]:
            lines.append(f"\t@printf '  %-15s\\n' '{target}'")
    else:
        lines.append("\t@echo \"  (none found)\"")

    lines.extend(
        [
            "\t@echo \"\"",
            "\t@echo \"Usage: make <target> KEY=VALUE ...\"",
            "\t@echo \"       make bootstrap\"",
            "\t@echo \"       make add MODULE=<name>\"",
            "",
            "bootstrap:",
            f"\t@$(PYTHON) {module_relpath.get('bootstrap-make', str(PYTHON_MODULES_DIR / 'bootstrap-make.py'))}",
            "",
            "add:",
            "\t@test -n \"$(MODULE)\" || (echo \"Usage: make add MODULE=<name>\" && exit 1)",
            f"\t@$(PYTHON) {module_relpath.get('bootstrap-make', str(PYTHON_MODULES_DIR / 'bootstrap-make.py'))} add --module \"$(MODULE)\"",
            "",
        ]
    )

    # Add special usage documentation for join-stages
    lines.extend(
        [
            "\t@echo \"\"",
            "\t@echo \"join-stages: Chain multiple stages together:\"",
            "\t@echo \"  make join-stages stage1 stage2 ...\"",
            "",
        ]
    )

    for module in modules:
        target = make_target_name(module)
        relpath = module_relpath[target]

        # Special handling for join-stages - it needs to receive additional stages as arguments
        if target == "join-stages":
            # Use MAKECMDGOALS to get all goals, filter out 'join-stages' itself
            recipe = f"\t@$(PYTHON) {relpath} $(filter-out join-stages,$(MAKECMDGOALS))"
        else:
            # Each target simply runs the Python script - args passed via command-line KEY=VALUE pairs
            recipe = f"\t@$(PYTHON) {relpath}"

        lines.extend(
            [
                f"{target}:",
                recipe,
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def write_makefile(directory: Path, content: str) -> Path:
    """Write Makefile content into the given directory."""
    makefile_path = directory / "Makefile"
    makefile_path.write_text(content, encoding="utf-8")
    return makefile_path


def normalize_module_name(raw_name: str) -> str:
    """Normalize user input into a safe Python module filename stem."""
    module_name = raw_name.strip()
    if module_name.endswith(".py"):
        module_name = module_name[:-3]

    if not module_name:
        raise ValueError("module name must not be empty")

    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_-]*", module_name):
        raise ValueError(
            "module name must start with a letter/underscore and contain only letters, "
            "numbers, underscores, or hyphens"
        )

    return module_name


def build_library_module_content() -> str:
    """Shared helpers imported by scaffolded modules."""
    return """\
\"\"\"Shared utilities for generated development modules.\"\"\"

from __future__ import annotations


def todo(feature: str) -> None:
    \"\"\"Raise a clear placeholder error for unfinished functionality.\"\"\"
    raise NotImplementedError(f\"Implement: {feature}\")


def run(main_func) -> int:
    \"\"\"Run a main function with a consistent KeyboardInterrupt exit code.\"\"\"
    try:
        return int(main_func())
    except KeyboardInterrupt:
        return 130
"""


def build_module_content(module_name: str) -> str:
    """Create scaffold content for a new Python module."""
    return f"""\
\"\"\"{module_name}: generated module scaffold.\"\"\"

from __future__ import annotations

from {Path(LIBRARY_MODULE_FILENAME).stem} import run, todo


def main() -> int:
    todo(\"{module_name}.main\")
    return 0


if __name__ == \"__main__\":
    raise SystemExit(run(main))
"""


def ensure_library_module(directory: Path) -> Path:
    """Create the shared library module if it doesn't already exist."""
    library_path = directory / LIBRARY_MODULE_FILENAME
    if not library_path.exists():
        library_path.write_text(build_library_module_content(), encoding="utf-8")
    return library_path


def add_module(directory: Path, module_name: str) -> Path:
    """Create a new module scaffold inside ``src/python/`` and ensure shared helpers exist."""
    normalized_name = normalize_module_name(module_name)
    modules_dir = directory / PYTHON_MODULES_DIR
    modules_dir.mkdir(parents=True, exist_ok=True)
    module_path = modules_dir / f"{normalized_name}.py"

    if module_path.exists():
        raise FileExistsError(f"{module_path.name} already exists")

    ensure_library_module(modules_dir)
    module_path.write_text(build_module_content(normalized_name), encoding="utf-8")
    return module_path


def bootstrap(directory: Path) -> Path:
    """Generate or refresh the Makefile from current Python modules.

    Modules are discovered under ``src/python/`` relative to ``directory``.
    The generated Makefile uses paths relative to ``directory`` so the
    project remains portable.
    """
    modules_dir = directory / PYTHON_MODULES_DIR
    modules = discover_python_modules(modules_dir) if modules_dir.is_dir() else []
    # Convert to paths relative to the project root so the Makefile stays portable.
    relative_modules = [
        module.relative_to(directory) if module.is_absolute() else module
        for module in modules
    ]
    content = build_makefile_content(relative_modules)
    makefile_path = write_makefile(directory, content)

    print(f"Wrote {makefile_path}")
    if relative_modules:
        print("Registered targets:", ", ".join(make_target_name(module) for module in relative_modules))
    else:
        print("No Python modules found in current folder.")

    return makefile_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Makefile recipes for Python modules in the current directory."
    )
    subparsers = parser.add_subparsers(dest="command")

    add_parser = subparsers.add_parser("add", help="Create a new Python module scaffold")
    add_parser.add_argument("--module", required=True, help="Module name, with or without .py")

    return parser.parse_args()


def main() -> int:
    args = parse_args()
    current_dir = Path.cwd()

    if args.command == "add":
        try:
            module_path = add_module(current_dir, args.module)
        except (ValueError, FileExistsError) as exc:
            print(f"Error: {exc}")
            return 1

        print(f"Created module: {module_path}")
        library_path = current_dir / PYTHON_MODULES_DIR / LIBRARY_MODULE_FILENAME
        if library_path.exists():
            print(f"Shared library available at: {library_path}")
        bootstrap(current_dir)
        return 0

    bootstrap(current_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())